#!/bin/bash
set -e

SCRIPT_NAME=$(basename $0)
LOG_NAME=${SCRIPT_NAME}.log
LOG_FILE=/root/${LOG_NAME}

log(){
#echo $1
#echo $1 >> $LOG_FILE
logger $1 -t $SCRIPT_NAME
}

MYSQL_CONTAILER_FOLDER=/root/mysql
MYSQL_CONTAINER=$(docker ps -a | grep witi/debian_hair_mysql | awk '{print $1}')
MAX_KEEP=3
CDATE=`date +%Y%m%d%H%M%S`

mkdir -p $MYSQL_CONTAILER_FOLDER
log "stop mysql"
docker stop $MYSQL_CONTAINER
log "backup mysql"
docker export $MYSQL_CONTAINER | gzip -c > $MYSQL_CONTAILER_FOLDER/mysql.$CDATE.tgz
log "start mysql"
docker start $MYSQL_CONTAINER

cd $MYSQL_CONTAILER_FOLDER
if [[ $(ls -tl | wc -l) > $MAX_KEEP ]];then
  log "cleanup backups"
  ls -t | sed -e "1,${MAX_KEEP}d" | xargs -d '\n' rm -rvf | logger -t $SCRIPT_NAME
fi
